use crate::{Cpu6502, function};

#[derive(Clone, Copy)]
pub enum AddressingMode {
    Implied,
    Immediate,
    ZeroPage,
    ZeroPageX,
    ZeroPageY,
    Absolute,
    AbsoluteX,
    AbsoluteY,
    Indirect,
    IndirectX,
    IndirectY,
    Relative,
    Accumulator,
}

impl AddressingMode {
    pub fn get_address(&self, cpu: &mut Cpu6502) -> u16 {
        match self {
            AddressingMode::Implied => 0,
            AddressingMode::Immediate => {
                cpu.pc += 1;
                cpu.pc
            },
            AddressingMode::ZeroPage => cpu.read_byte(cpu.pc + 1) as u16,
            AddressingMode::ZeroPageX => (cpu.read_byte(cpu.pc + 1) + cpu.x) as u16,
            AddressingMode::ZeroPageY => (cpu.read_byte(cpu.pc + 1) + cpu.y) as u16,
            AddressingMode::Absolute => cpu.read_word(cpu.pc + 1),
            AddressingMode::AbsoluteX => cpu.read_word(cpu.pc + 1) + cpu.x as u16,
            AddressingMode::AbsoluteY => cpu.read_word(cpu.pc + 1) + cpu.y as u16,
            AddressingMode::Indirect => {
                let address = cpu.read_word(cpu.pc + 1);
                cpu.read_word(address)
            },
            AddressingMode::IndirectX => {
                let address = cpu.read_byte(cpu.pc + 1) + cpu.x;
                cpu.read_word(address as u16)
            }
            AddressingMode::IndirectY => {
                let address = cpu.read_byte(cpu.pc + 1);
                cpu.read_word(address as u16) + cpu.y as u16
            }
            AddressingMode::Relative => cpu.read_byte(cpu.pc + 1) as u16,
            AddressingMode::Accumulator => cpu.a.into(),
        }
    }
}

#[derive(Clone, Copy)]
pub struct Instruction<'a> {
    pub name: &'a str,
    pub opcode: u8,
    pub addressing_mode: AddressingMode,
    pub cycles: u8,
    pub length: u8,
    pub execute: fn(&mut Cpu6502, AddressingMode),
}

pub const INSTRUCTIONS: [Instruction; 256] = [
    Instruction {
        name: "BRK",
        opcode: 0x00,
        addressing_mode: AddressingMode::Implied,
        cycles: 7,
        length: 1,
        execute: function::brk,
    },
    Instruction {
        name: "ORA",
        opcode: 0x01,
        addressing_mode: AddressingMode::IndirectX,
        cycles: 6,
        length: 2,
        execute: function::ora,
    },
    Instruction {
        name: "KIL",
        opcode: 0x02,
        addressing_mode: AddressingMode::Implied,
        cycles: 0,
        length: 1,
        execute: function::kil,
    },
    Instruction {
        name: "SLO",
        opcode: 0x03,
        addressing_mode: AddressingMode::IndirectX,
        cycles: 8,
        length: 2,
        execute: function::slo,
    },
    Instruction {
        name: "NOP",
        opcode: 0x04,
        addressing_mode: AddressingMode::ZeroPage,
        cycles: 3,
        length: 2,
        execute: function::nop,
    },
    Instruction {
        name: "ORA",
        opcode: 0x05,
        addressing_mode: AddressingMode::ZeroPage,
        cycles: 3,
        length: 2,
        execute: function::ora,
    },
    Instruction {
        name: "ASL",
        opcode: 0x06,
        addressing_mode: AddressingMode::ZeroPage,
        cycles: 5,
        length: 2,
        execute: function::asl,
    },
    Instruction {
        name: "SLO",
        opcode: 0x07,
        addressing_mode: AddressingMode::ZeroPage,
        cycles: 5,
        length: 2,
        execute: function::slo,
    },
    Instruction {
        name: "PHP",
        opcode: 0x08,
        addressing_mode: AddressingMode::Implied,
        cycles: 3,
        length: 1,
        execute: function::php,
    },
    Instruction {
        name: "ORA",
        opcode: 0x09,
        addressing_mode: AddressingMode::Immediate,
        cycles: 2,
        length: 2,
        execute: function::ora,
    },
    Instruction {
        name: "ASL",
        opcode: 0x0A,
        addressing_mode: AddressingMode::Accumulator,
        cycles: 2,
        length: 1,
        execute: function::asl,
    },
    Instruction {
        name: "ANC",
        opcode: 0x0B,
        addressing_mode: AddressingMode::Immediate,
        cycles: 2,
        length: 2,
        execute: function::anc,
    },
    Instruction {
        name: "NOP",
        opcode: 0x0C,
        addressing_mode: AddressingMode::Absolute,
        cycles: 4,
        length: 3,
        execute: function::nop,
    },
    Instruction {
        name: "ORA",
        opcode: 0x0D,
        addressing_mode: AddressingMode::Absolute,
        cycles: 4,
        length: 3,
        execute: function::ora,
    },
    Instruction {
        name: "ASL",
        opcode: 0x0E,
        addressing_mode: AddressingMode::Absolute,
        cycles: 6,
        length: 3,
        execute: function::asl,
    },
    Instruction {
        name: "SLO",
        opcode: 0x0F,
        addressing_mode: AddressingMode::Absolute,
        cycles: 6,
        length: 3,
        execute: function::slo,
    },
    Instruction {
        name: "BPL",
        opcode: 0x10,
        addressing_mode: AddressingMode::Relative,
        cycles: 2,
        length: 2,
        execute: function::bpl,
    },
    Instruction {
        name: "ORA",
        opcode: 0x11,
        addressing_mode: AddressingMode::IndirectY,
        cycles: 5,
        length: 2,
        execute: function::ora,
    },
    Instruction {
        name: "KIL",
        opcode: 0x12,
        addressing_mode: AddressingMode::Implied,
        cycles: 0,
        length: 1,
        execute: function::kil,
    },
    Instruction {
        name: "SLO",
        opcode: 0x13,
        addressing_mode: AddressingMode::IndirectY,
        cycles: 8,
        length: 2,
        execute: function::slo,
    },
    Instruction {
        name: "NOP",
        opcode: 0x14,
        addressing_mode: AddressingMode::ZeroPageX,
        cycles: 4,
        length: 2,
        execute: function::nop,
    },
    Instruction {
        name: "ORA",
        opcode: 0x15,
        addressing_mode: AddressingMode::ZeroPageX,
        cycles: 4,
        length: 2,
        execute: function::ora,
    },
    Instruction {
        name: "ASL",
        opcode: 0x16,
        addressing_mode: AddressingMode::ZeroPageX,
        cycles: 6,
        length: 2,
        execute: function::asl,
    },
    Instruction {
        name: "SLO",
        opcode: 0x17,
        addressing_mode: AddressingMode::ZeroPageX,
        cycles: 6,
        length: 2,
        execute: function::slo,
    },
    Instruction {
        name: "CLC",
        opcode: 0x18,
        addressing_mode: AddressingMode::Implied,
        cycles: 2,
        length: 1,
        execute: function::clc,
    },
    Instruction {
        name: "ORA",
        opcode: 0x19,
        addressing_mode: AddressingMode::AbsoluteY,
        cycles: 4,
        length: 3,
        execute: function::ora,
    },
    Instruction {
        name: "NOP",
        opcode: 0x1A,
        addressing_mode: AddressingMode::Implied,
        cycles: 2,
        length: 1,
        execute: function::nop,
    },
    Instruction {
        name: "SLO",
        opcode: 0x1B,
        addressing_mode: AddressingMode::AbsoluteY,
        cycles: 7,
        length: 3,
        execute: function::slo,
    },
    Instruction {
        name: "NOP",
        opcode: 0x1C,
        addressing_mode: AddressingMode::AbsoluteX,
        cycles: 4,
        length: 3,
        execute: function::nop,
    },
    Instruction {
        name: "ORA",
        opcode: 0x1D,
        addressing_mode: AddressingMode::AbsoluteX,
        cycles: 4,
        length: 3,
        execute: function::ora,
    },
    Instruction {
        name: "ASL",
        opcode: 0x1E,
        addressing_mode: AddressingMode::AbsoluteX,
        cycles: 7,
        length: 3,
        execute: function::asl,
    },
    Instruction {
        name: "SLO",
        opcode: 0x1F,
        addressing_mode: AddressingMode::AbsoluteX,
        cycles: 7,
        length: 3,
        execute: function::slo,
    },
    Instruction {
        name: "JSR",
        opcode: 0x20,
        addressing_mode: AddressingMode::Absolute,
        cycles: 6,
        length: 3,
        execute: function::jsr,
    },
    Instruction {
        name: "AND",
        opcode: 0x21,
        addressing_mode: AddressingMode::IndirectX,
        cycles: 6,
        length: 2,
        execute: function::and,
    },
    Instruction {
        name: "KIL",
        opcode: 0x22,
        addressing_mode: AddressingMode::Implied,
        cycles: 0,
        length: 1,
        execute: function::kil,
    },
    Instruction {
        name: "RLA",
        opcode: 0x23,
        addressing_mode: AddressingMode::IndirectX,
        cycles: 8,
        length: 2,
        execute: function::rla,
    },
    Instruction {
        name: "BIT",
        opcode: 0x24,
        addressing_mode: AddressingMode::ZeroPage,
        cycles: 3,
        length: 2,
        execute: function::bit,
    },
    Instruction {
        name: "AND",
        opcode: 0x25,
        addressing_mode: AddressingMode::ZeroPage,
        cycles: 3,
        length: 2,
        execute: function::and,
    },
    Instruction {
        name: "ROL",
        opcode: 0x26,
        addressing_mode: AddressingMode::ZeroPage,
        cycles: 5,
        length: 2,
        execute: function::rol,
    },
    Instruction {
        name: "RLA",
        opcode: 0x27,
        addressing_mode: AddressingMode::ZeroPage,
        cycles: 5,
        length: 2,
        execute: function::rla,
    },
    Instruction {
        name: "PLP",
        opcode: 0x28,
        addressing_mode: AddressingMode::Implied,
        cycles: 4,
        length: 1,
        execute: function::plp,
    },
    Instruction {
        name: "AND",
        opcode: 0x29,
        addressing_mode: AddressingMode::Immediate,
        cycles: 2,
        length: 2,
        execute: function::and,
    },
    Instruction {
        name: "ROL",
        opcode: 0x2A,
        addressing_mode: AddressingMode::Accumulator,
        cycles: 2,
        length: 1,
        execute: function::rol,
    },
    Instruction {
        name: "ANC",
        opcode: 0x2B,
        addressing_mode: AddressingMode::Immediate,
        cycles: 2,
        length: 2,
        execute: function::anc,
    },
    Instruction {
        name: "BIT",
        opcode: 0x2C,
        addressing_mode: AddressingMode::Absolute,
        cycles: 4,
        length: 3,
        execute: function::bit,
    },
    Instruction {
        name: "AND",
        opcode: 0x2D,
        addressing_mode: AddressingMode::Absolute,
        cycles: 4,
        length: 3,
        execute: function::and,
    },
    Instruction {
        name: "ROL",
        opcode: 0x2E,
        addressing_mode: AddressingMode::Absolute,
        cycles: 6,
        length: 3,
        execute: function::rol,
    },
    Instruction {
        name: "RLA",
        opcode: 0x2F,
        addressing_mode: AddressingMode::Absolute,
        cycles: 6,
        length: 3,
        execute: function::rla,
    },
    Instruction {
        name: "BMI",
        opcode: 0x30,
        addressing_mode: AddressingMode::Relative,
        cycles: 2,
        length: 2,
        execute: function::bmi,
    },
    Instruction {
        name: "AND",
        opcode: 0x31,
        addressing_mode: AddressingMode::IndirectY,
        cycles: 5,
        length: 2,
        execute: function::and,
    },
    Instruction {
        name: "KIL",
        opcode: 0x32,
        addressing_mode: AddressingMode::Implied,
        cycles: 0,
        length: 1,
        execute: function::kil,
    },
    Instruction {
        name: "RLA",
        opcode: 0x33,
        addressing_mode: AddressingMode::IndirectY,
        cycles: 8,
        length: 2,
        execute: function::rla,
    },
    Instruction {
        name: "NOP",
        opcode: 0x34,
        addressing_mode: AddressingMode::ZeroPageX,
        cycles: 4,
        length: 2,
        execute: function::nop,
    },
    Instruction {
        name: "AND",
        opcode: 0x35,
        addressing_mode: AddressingMode::ZeroPageX,
        cycles: 4,
        length: 2,
        execute: function::and,
    },
    Instruction {
        name: "ROL",
        opcode: 0x36,
        addressing_mode: AddressingMode::ZeroPageX,
        cycles: 6,
        length: 2,
        execute: function::rol,
    },
    Instruction {
        name: "RLA",
        opcode: 0x37,
        addressing_mode: AddressingMode::ZeroPageX,
        cycles: 6,
        length: 2,
        execute: function::rla,
    },
    Instruction {
        name: "SEC",
        opcode: 0x38,
        addressing_mode: AddressingMode::Implied,
        cycles: 2,
        length: 1,
        execute: function::sec,
    },
    Instruction {
        name: "AND",
        opcode: 0x39,
        addressing_mode: AddressingMode::AbsoluteY,
        cycles: 4,
        length: 3,
        execute: function::and,
    },
    Instruction {
        name: "NOP",
        opcode: 0x3A,
        addressing_mode: AddressingMode::Implied,
        cycles: 2,
        length: 1,
        execute: function::nop,
    },
    Instruction {
        name: "RLA",
        opcode: 0x3B,
        addressing_mode: AddressingMode::AbsoluteY,
        cycles: 7,
        length: 3,
        execute: function::rla,
    },
    Instruction {
        name: "NOP",
        opcode: 0x3C,
        addressing_mode: AddressingMode::AbsoluteX,
        cycles: 4,
        length: 3,
        execute: function::nop,
    },
    Instruction {
        name: "AND",
        opcode: 0x3D,
        addressing_mode: AddressingMode::AbsoluteX,
        cycles: 4,
        length: 3,
        execute: function::and,
    },
    Instruction {
        name: "ROL",
        opcode: 0x3E,
        addressing_mode: AddressingMode::AbsoluteX,
        cycles: 7,
        length: 3,
        execute: function::rol,
    },
    Instruction {
        name: "RLA",
        opcode: 0x3F,
        addressing_mode: AddressingMode::AbsoluteX,
        cycles: 7,
        length: 3,
        execute: function::rla,
    },
    Instruction {
        name: "RTI",
        opcode: 0x40,
        addressing_mode: AddressingMode::Implied,
        cycles: 6,
        length: 1,
        execute: function::rti,
    },
    Instruction {
        name: "EOR",
        opcode: 0x41,
        addressing_mode: AddressingMode::IndirectX,
        cycles: 6,
        length: 2,
        execute: function::eor,
    },
    Instruction {
        name: "KIL",
        opcode: 0x42,
        addressing_mode: AddressingMode::Implied,
        cycles: 0,
        length: 1,
        execute: function::kil,
    },
    Instruction {
        name: "SRE",
        opcode: 0x43,
        addressing_mode: AddressingMode::IndirectX,
        cycles: 8,
        length: 2,
        execute: function::sre,
    },
    Instruction {
        name: "NOP",
        opcode: 0x44,
        addressing_mode: AddressingMode::ZeroPage,
        cycles: 3,
        length: 2,
        execute: function::nop,
    },
    Instruction {
        name: "EOR",
        opcode: 0x45,
        addressing_mode: AddressingMode::ZeroPage,
        cycles: 3,
        length: 2,
        execute: function::eor,
    },
    Instruction {
        name: "LSR",
        opcode: 0x46,
        addressing_mode: AddressingMode::ZeroPage,
        cycles: 5,
        length: 2,
        execute: function::lsr,
    },
    Instruction {
        name: "SRE",
        opcode: 0x47,
        addressing_mode: AddressingMode::ZeroPage,
        cycles: 5,
        length: 2,
        execute: function::sre,
    },
    Instruction {
        name: "PHA",
        opcode: 0x48,
        addressing_mode: AddressingMode::Implied,
        cycles: 3,
        length: 1,
        execute: function::pha,
    },
    Instruction {
        name: "EOR",
        opcode: 0x49,
        addressing_mode: AddressingMode::Immediate,
        cycles: 2,
        length: 2,
        execute: function::eor,
    },
    Instruction {
        name: "LSR",
        opcode: 0x4A,
        addressing_mode: AddressingMode::Accumulator,
        cycles: 2,
        length: 1,
        execute: function::lsr,
    },
    Instruction {
        name: "ASR",
        opcode: 0x4B,
        addressing_mode: AddressingMode::Immediate,
        cycles: 2,
        length: 2,
        execute: function::asr,
    },
    Instruction {
        name: "JMP",
        opcode: 0x4C,
        addressing_mode: AddressingMode::Absolute,
        cycles: 3,
        length: 3,
        execute: function::jmp,
    },
    Instruction {
        name: "EOR",
        opcode: 0x4D,
        addressing_mode: AddressingMode::Absolute,
        cycles: 4,
        length: 3,
        execute: function::eor,
    },
    Instruction {
        name: "LSR",
        opcode: 0x4E,
        addressing_mode: AddressingMode::Absolute,
        cycles: 6,
        length: 3,
        execute: function::lsr,
    },
    Instruction {
        name: "SRE",
        opcode: 0x4F,
        addressing_mode: AddressingMode::Absolute,
        cycles: 6,
        length: 3,
        execute: function::sre,
    },
    Instruction {
        name: "BVC",
        opcode: 0x50,
        addressing_mode: AddressingMode::Relative,
        cycles: 2,
        length: 2,
        execute: function::bvc,
    },
    Instruction {
        name: "EOR",
        opcode: 0x51,
        addressing_mode: AddressingMode::IndirectY,
        cycles: 5,
        length: 2,
        execute: function::eor,
    },
    Instruction {
        name: "KIL",
        opcode: 0x52,
        addressing_mode: AddressingMode::Implied,
        cycles: 0,
        length: 1,
        execute: function::kil,
    },
    Instruction {
        name: "SRE",
        opcode: 0x53,
        addressing_mode: AddressingMode::IndirectY,
        cycles: 8,
        length: 2,
        execute: function::sre,
    },
    Instruction {
        name: "NOP",
        opcode: 0x54,
        addressing_mode: AddressingMode::ZeroPageX,
        cycles: 4,
        length: 2,
        execute: function::nop,
    },
    Instruction {
        name: "EOR",
        opcode: 0x55,
        addressing_mode: AddressingMode::ZeroPageX,
        cycles: 4,
        length: 2,
        execute: function::eor,
    },
    Instruction {
        name: "LSR",
        opcode: 0x56,
        addressing_mode: AddressingMode::ZeroPageX,
        cycles: 6,
        length: 2,
        execute: function::lsr,
    },
    Instruction {
        name: "SRE",
        opcode: 0x57,
        addressing_mode: AddressingMode::ZeroPageX,
        cycles: 6,
        length: 2,
        execute: function::sre,
    },
    Instruction {
        name: "CLI",
        opcode: 0x58,
        addressing_mode: AddressingMode::Implied,
        cycles: 2,
        length: 1,
        execute: function::cli,
    },
    Instruction {
        name: "EOR",
        opcode: 0x59,
        addressing_mode: AddressingMode::AbsoluteY,
        cycles: 4,
        length: 3,
        execute: function::eor,
    },
    Instruction {
        name: "NOP",
        opcode: 0x5A,
        addressing_mode: AddressingMode::Implied,
        cycles: 2,
        length: 1,
        execute: function::nop,
    },
    Instruction {
        name: "SRE",
        opcode: 0x5B,
        addressing_mode: AddressingMode::AbsoluteY,
        cycles: 7,
        length: 3,
        execute: function::sre,
    },
    Instruction {
        name: "NOP",
        opcode: 0x5C,
        addressing_mode: AddressingMode::AbsoluteX,
        cycles: 4,
        length: 3,
        execute: function::nop,
    },
    Instruction {
        name: "EOR",
        opcode: 0x5D,
        addressing_mode: AddressingMode::AbsoluteX,
        cycles: 4,
        length: 3,
        execute: function::eor,
    },
    Instruction {
        name: "LSR",
        opcode: 0x5E,
        addressing_mode: AddressingMode::AbsoluteX,
        cycles: 7,
        length: 3,
        execute: function::lsr,
    },
Instruction {
        name: "SRE",
        opcode: 0x5F,
        addressing_mode: AddressingMode::AbsoluteX,
        cycles: 7,
        length: 3,
        execute: function::sre,
    },
    Instruction {
        name: "RTS",
        opcode: 0x60,
        addressing_mode: AddressingMode::Implied,
        cycles: 6,
        length: 1,
        execute: function::rts,
    },
    Instruction {
        name: "ADC",
        opcode: 0x61,
        addressing_mode: AddressingMode::IndirectX,
        cycles: 6,
        length: 2,
        execute: function::adc,
    },
    Instruction {
        name: "KIL",
        opcode: 0x62,
        addressing_mode: AddressingMode::Implied,
        cycles: 0,
        length: 1,
        execute: function::kil,
    },
    Instruction {
        name: "RRA",
        opcode: 0x63,
        addressing_mode: AddressingMode::IndirectX,
        cycles: 8,
        length: 2,
        execute: function::rra,
    },
    Instruction {
        name: "NOP",
        opcode: 0x64,
        addressing_mode: AddressingMode::ZeroPage,
        cycles: 3,
        length: 2,
        execute: function::nop,
    },
    Instruction {
        name: "ADC",
        opcode: 0x65,
        addressing_mode: AddressingMode::ZeroPage,
        cycles: 3,
        length: 2,
        execute: function::adc,
    },
    Instruction {
        name: "ROR",
        opcode: 0x66,
        addressing_mode: AddressingMode::ZeroPage,
        cycles: 5,
        length: 2,
        execute: function::ror,
    },
    Instruction {
        name: "RRA",
        opcode: 0x67,
        addressing_mode: AddressingMode::ZeroPage,
        cycles: 5,
        length: 2,
        execute: function::rra,
    },
    Instruction {
        name: "PLA",
        opcode: 0x68,
        addressing_mode: AddressingMode::Implied,
        cycles: 4,
        length: 1,
        execute: function::pla,
    },
    Instruction {
        name: "ADC",
        opcode: 0x69,
        addressing_mode: AddressingMode::Immediate,
        cycles: 2,
        length: 2,
        execute: function::adc,
    },
    Instruction {
        name: "ROR",
        opcode: 0x6A,
        addressing_mode: AddressingMode::Accumulator,
        cycles: 2,
        length: 1,
        execute: function::ror,
    },
    Instruction {
        name: "ARR",
        opcode: 0x6B,
        addressing_mode: AddressingMode::Immediate,
        cycles: 2,
        length: 2,
        execute: function::arr,
    },
    Instruction {
        name: "JMP",
        opcode: 0x6C,
        addressing_mode: AddressingMode::Indirect,
        cycles: 5,
        length: 3,
        execute: function::jmp,
    },
    Instruction {
        name: "ADC",
        opcode: 0x6D,
        addressing_mode: AddressingMode::Absolute,
        cycles: 4,
        length: 3,
        execute: function::adc,
    },
    Instruction {
        name: "ROR",
        opcode: 0x6E,
        addressing_mode: AddressingMode::Absolute,
        cycles: 6,
        length: 3,
        execute: function::ror,
    },
    Instruction {
        name: "RRA",
        opcode: 0x6F,
        addressing_mode: AddressingMode::Absolute,
        cycles: 6,
        length: 3,
        execute: function::rra,
    },
    Instruction {
        name: "BVS",
        opcode: 0x70,
        addressing_mode: AddressingMode::Relative,
        cycles: 2,
        length: 2,
        execute: function::bvs,
    },
    Instruction {
        name: "ADC",
        opcode: 0x71,
        addressing_mode: AddressingMode::IndirectY,
        cycles: 5,
        length: 2,
        execute: function::adc,
    },
    Instruction {
        name: "KIL",
        opcode: 0x72,
        addressing_mode: AddressingMode::Implied,
        cycles: 0,
        length: 1,
        execute: function::kil,
    },
    Instruction {
        name: "RRA",
        opcode: 0x73,
        addressing_mode: AddressingMode::IndirectY,
        cycles: 8,
        length: 2,
        execute: function::rra,
    },
    Instruction {
        name: "NOP",
        opcode: 0x74,
        addressing_mode: AddressingMode::ZeroPageX,
        cycles: 4,
        length: 2,
        execute: function::nop,
    },
    Instruction {
        name: "ADC",
        opcode: 0x75,
        addressing_mode: AddressingMode::ZeroPageX,
        cycles: 4,
        length: 2,
        execute: function::adc,
    },
    Instruction {
        name: "ROR",
        opcode: 0x76,
        addressing_mode: AddressingMode::ZeroPageX,
        cycles: 6,
        length: 2,
        execute: function::ror,
    },
    Instruction {
        name: "RRA",
        opcode: 0x77,
        addressing_mode: AddressingMode::ZeroPageX,
        cycles: 6,
        length: 2,
        execute: function::rra,
    },
    Instruction {
        name: "SEI",
        opcode: 0x78,
        addressing_mode: AddressingMode::Implied,
        cycles: 2,
        length: 1,
        execute: function::sei,
    },
    Instruction {
        name: "ADC",
        opcode: 0x79,
        addressing_mode: AddressingMode::AbsoluteY,
        cycles: 4,
        length: 3,
        execute: function::adc,
    },
    Instruction {
        name: "NOP",
        opcode: 0x7A,
        addressing_mode: AddressingMode::Implied,
        cycles: 2,
        length: 1,
        execute: function::nop,
    },
    Instruction {
        name: "RRA",
        opcode: 0x7B,
        addressing_mode: AddressingMode::AbsoluteY,
        cycles: 7,
        length: 3,
        execute: function::rra,
    },
    Instruction {
        name: "NOP",
        opcode: 0x7C,
        addressing_mode: AddressingMode::AbsoluteX,
        cycles: 4,
        length: 3,
        execute: function::nop,
    },
    Instruction {
        name: "ADC",
        opcode: 0x7D,
        addressing_mode: AddressingMode::AbsoluteX,
        cycles: 4,
        length: 3,
        execute: function::adc,
    },
    Instruction {
        name: "ROR",
        opcode: 0x7E,
        addressing_mode: AddressingMode::AbsoluteX,
        cycles: 7,
        length: 3,
        execute: function::ror,
    },
    Instruction {
        name: "RRA",
        opcode: 0x7F,
        addressing_mode: AddressingMode::AbsoluteX,
        cycles: 7,
        length: 3,
        execute: function::rra,
    },
    Instruction {
        name: "NOP",
        opcode: 0x80,
        addressing_mode: AddressingMode::Immediate,
        cycles: 2,
        length: 2,
        execute: function::nop,
    },
    Instruction {
        name: "STA",
        opcode: 0x81,
        addressing_mode: AddressingMode::IndirectX,
        cycles: 6,
        length: 2,
        execute: function::sta,
    },
    Instruction {
        name: "NOP",
        opcode: 0x82,
        addressing_mode: AddressingMode::Immediate,
        cycles: 2,
        length: 2,
        execute: function::nop,
    },
    Instruction {
        name: "SAX",
        opcode: 0x83,
        addressing_mode: AddressingMode::IndirectX,
        cycles: 6,
        length: 2,
        execute: function::sax,
    },
    Instruction {
        name: "STY",
        opcode: 0x84,
        addressing_mode: AddressingMode::ZeroPage,
        cycles: 3,
        length: 2,
        execute: function::sty,
    },
    Instruction {
        name: "STA",
        opcode: 0x85,
        addressing_mode: AddressingMode::ZeroPage,
        cycles: 3,
        length: 2,
        execute: function::sta,
    },
    Instruction {
        name: "STX",
        opcode: 0x86,
        addressing_mode: AddressingMode::ZeroPage,
        cycles: 3,
        length: 2,
        execute: function::stx,
    },
    Instruction {
        name: "SAX",
        opcode: 0x87,
        addressing_mode: AddressingMode::ZeroPage,
        cycles: 3,
        length: 2,
        execute: function::sax,
    },
    Instruction {
        name: "DEY",
        opcode: 0x88,
        addressing_mode: AddressingMode::Implied,
        cycles: 2,
        length: 1,
        execute: function::dey,
    },
    Instruction {
        name: "NOP",
        opcode: 0x89,
        addressing_mode: AddressingMode::Immediate,
        cycles: 2,
        length: 2,
        execute: function::nop,
    },
    Instruction {
        name: "TXA",
        opcode: 0x8A,
        addressing_mode: AddressingMode::Implied,
        cycles: 2,
        length: 1,
        execute: function::txa,
    },
    Instruction {
        name: "XAA",
        opcode: 0x8B,
        addressing_mode: AddressingMode::Immediate,
        cycles: 2,
        length: 2,
        execute: function::xaa,
    },
    Instruction {
        name: "STY",
        opcode: 0x8C,
        addressing_mode: AddressingMode::Absolute,
        cycles: 4,
        length: 3,
        execute: function::sty,
    },
    Instruction {
        name: "STA",
        opcode: 0x8D,
        addressing_mode: AddressingMode::Absolute,
        cycles: 4,
        length: 3,
        execute: function::sta,
    },
    Instruction {
        name: "STX",
        opcode: 0x8E,
        addressing_mode: AddressingMode::Absolute,
        cycles: 4,
        length: 3,
        execute: function::stx,
    },
    Instruction {
        name: "SAX",
        opcode: 0x8F,
        addressing_mode: AddressingMode::Absolute,
        cycles: 4,
        length: 3,
        execute: function::sax,
    },
    Instruction {
        name: "BCC",
        opcode: 0x90,
        addressing_mode: AddressingMode::Relative,
        cycles: 2,
        length: 2,
        execute: function::bcc,
    },
    Instruction {
        name: "STA",
        opcode: 0x91,
        addressing_mode: AddressingMode::IndirectY,
        cycles: 6,
        length: 2,
        execute: function::sta,
    },
    Instruction {
        name: "KIL",
        opcode: 0x92,
        addressing_mode: AddressingMode::Implied,
        cycles: 0,
        length: 1,
        execute: function::kil,
    },
    Instruction {
        name: "AHX",
        opcode: 0x93,
        addressing_mode: AddressingMode::IndirectY,
        cycles: 6,
        length: 2,
        execute: function::ahx,
    },
    Instruction {
        name: "STY",
        opcode: 0x94,
        addressing_mode: AddressingMode::ZeroPageX,
        cycles: 4,
        length: 2,
        execute: function::sty,
    },
    Instruction {
        name: "STA",
        opcode: 0x95,
        addressing_mode: AddressingMode::ZeroPageX,
        cycles: 4,
        length: 2,
        execute: function::sta,
    },
    Instruction {
        name: "STX",
        opcode: 0x96,
        addressing_mode: AddressingMode::ZeroPageY,
        cycles: 4,
        length: 2,
        execute: function::stx,
    },
    Instruction {
        name: "SAX",
        opcode: 0x97,
        addressing_mode: AddressingMode::ZeroPageY,
        cycles: 4,
        length: 2,
        execute: function::sax,
    },
    Instruction {
        name: "TYA",
        opcode: 0x98,
        addressing_mode: AddressingMode::Implied,
        cycles: 2,
        length: 1,
        execute: function::tya,
    },
    Instruction {
        name: "STA",
        opcode: 0x99,
        addressing_mode: AddressingMode::AbsoluteY,
        cycles: 5,
        length: 3,
        execute: function::sta,
    },
    Instruction {
        name: "TXS",
        opcode: 0x9A,
        addressing_mode: AddressingMode::Implied,
        cycles: 2,
        length: 1,
        execute: function::txs,
    },
    Instruction {
        name: "TAS",
        opcode: 0x9B,
        addressing_mode: AddressingMode::AbsoluteY,
        cycles: 5,
        length: 3,
        execute: function::tas,
    },
    Instruction {
        name: "SHY",
        opcode: 0x9C,
        addressing_mode: AddressingMode::AbsoluteX,
        cycles: 5,
        length: 3,
        execute: function::shy,
    },
    Instruction {
        name: "STA",
        opcode: 0x9D,
        addressing_mode: AddressingMode::AbsoluteX,
        cycles: 5,
        length: 3,
        execute: function::sta,
    },
    Instruction {
        name: "SHX",
        opcode: 0x9E,
        addressing_mode: AddressingMode::AbsoluteY,
        cycles: 5,
        length: 3,
        execute: function::shx,
    },
    Instruction {
        name: "AHX",
        opcode: 0x9F,
        addressing_mode: AddressingMode::AbsoluteY,
        cycles: 5,
        length: 3,
        execute: function::ahx,
    },
    Instruction {
        name: "LDY",
        opcode: 0xA0,
        addressing_mode: AddressingMode::Immediate,
        cycles: 2,
        length: 2,
        execute: function::ldy,
    },
    Instruction {
        name: "LDA",
        opcode: 0xA1,
        addressing_mode: AddressingMode::IndirectX,
        cycles: 6,
        length: 2,
        execute: function::lda,
    },
    Instruction {
        name: "LDX",
        opcode: 0xA2,
        addressing_mode: AddressingMode::Immediate,
        cycles: 2,
        length: 2,
        execute: function::ldx,
    },
    Instruction {
        name: "LAX",
        opcode: 0xA3,
        addressing_mode: AddressingMode::IndirectX,
        cycles: 6,
        length: 2,
        execute: function::lax,
    },
    Instruction {
        name: "LDY",
        opcode: 0xA4,
        addressing_mode: AddressingMode::ZeroPage,
        cycles: 3,
        length: 2,
        execute: function::ldy,
    },
    Instruction {
        name: "LDA",
        opcode: 0xA5,
        addressing_mode: AddressingMode::ZeroPage,
        cycles: 3,
        length: 2,
        execute: function::lda,
    },
    Instruction {
        name: "LDX",
        opcode: 0xA6,
        addressing_mode: AddressingMode::ZeroPage,
        cycles: 3,
        length: 2,
        execute: function::ldx,
    },
    Instruction {
        name: "LAX",
        opcode: 0xA7,
        addressing_mode: AddressingMode::ZeroPage,
        cycles: 3,
        length: 2,
        execute: function::lax,
    },
    Instruction {
        name: "TAY",
        opcode: 0xA8,
        addressing_mode: AddressingMode::Implied,
        cycles: 2,
        length: 1,
        execute: function::tay,
    },
    Instruction {
        name: "LDA",
        opcode: 0xA9,
        addressing_mode: AddressingMode::Immediate,
        cycles: 2,
        length: 2,
        execute: function::lda,
    },
    Instruction {
        name: "TAX",
        opcode: 0xAA,
        addressing_mode: AddressingMode::Implied,
        cycles: 2,
        length: 1,
        execute: function::tax,
    },
    Instruction {
        name: "LAX",
        opcode: 0xAB,
        addressing_mode: AddressingMode::Immediate,
        cycles: 2,
        length: 2,
        execute: function::lax,
    },
    Instruction {
        name: "LDY",
        opcode: 0xAC,
        addressing_mode: AddressingMode::Absolute,
        cycles: 4,
        length: 3,
        execute: function::ldy,
    },
    Instruction {
        name: "LDA",
        opcode: 0xAD,
        addressing_mode: AddressingMode::Absolute,
        cycles: 4,
        length: 3,
        execute: function::lda,
    },
    Instruction {
        name: "LDX",
        opcode: 0xAE,
        addressing_mode: AddressingMode::Absolute,
        cycles: 4,
        length: 3,
        execute: function::ldx,
    },
    Instruction {
        name: "LAX",
        opcode: 0xAF,
        addressing_mode: AddressingMode::Absolute,
        cycles: 4,
        length: 3,
        execute: function::lax,
    },
    Instruction {
        name: "BCS",
        opcode: 0xB0,
        addressing_mode: AddressingMode::Relative,
        cycles: 2,
        length: 2,
        execute: function::bcs,
    },
    Instruction {
        name: "LDA",
        opcode: 0xB1,
        addressing_mode: AddressingMode::IndirectY,
        cycles: 5,
        length: 2,
        execute: function::lda,
    },
    Instruction {
        name: "KIL",
        opcode: 0xB2,
        addressing_mode: AddressingMode::Implied,
        cycles: 0,
        length: 1,
        execute: function::kil,
    },
    Instruction {
        name: "LAX",
        opcode: 0xB3,
        addressing_mode: AddressingMode::IndirectY,
        cycles: 5,
        length: 2,
        execute: function::lax,
    },
    Instruction {
        name: "LDY",
        opcode: 0xB4,
        addressing_mode: AddressingMode::ZeroPageX,
        cycles: 4,
        length: 2,
        execute: function::ldy,
    },
    Instruction {
        name: "LDA",
        opcode: 0xB5,
        addressing_mode: AddressingMode::ZeroPageX,
        cycles: 4,
        length: 2,
        execute: function::lda,
    },
    Instruction {
        name: "LDX",
        opcode: 0xB6,
        addressing_mode: AddressingMode::ZeroPageY,
        cycles: 4,
        length: 2,
        execute: function::ldx,
    },
    Instruction {
        name: "LAX",
        opcode: 0xB7,
        addressing_mode: AddressingMode::ZeroPageY,
        cycles: 4,
        length: 2,
        execute: function::lax,
    },
    Instruction {
        name: "CLV",
        opcode: 0xB8,
        addressing_mode: AddressingMode::Implied,
        cycles: 2,
        length: 1,
        execute: function::clv,
    },
    Instruction {
        name: "LDA",
        opcode: 0xB9,
        addressing_mode: AddressingMode::AbsoluteY,
        cycles: 4,
        length: 3,
        execute: function::lda,
    },
    Instruction {
        name: "TSX",
        opcode: 0xBA,
        addressing_mode: AddressingMode::Implied,
        cycles: 2,
        length: 1,
        execute: function::tsx,
    },
    Instruction {
        name: "LAS",
        opcode: 0xBB,
        addressing_mode: AddressingMode::AbsoluteY,
        cycles: 4,
        length: 3,
        execute: function::las,
    },
    Instruction {
        name: "LDY",
        opcode: 0xBC,
        addressing_mode: AddressingMode::AbsoluteX,
        cycles: 4,
        length: 3,
        execute: function::ldy,
    },
    Instruction {
        name: "LDA",
        opcode: 0xBD,
        addressing_mode: AddressingMode::AbsoluteX,
        cycles: 4,
        length: 3,
        execute: function::lda,
    },
    Instruction {
        name: "LDX",
        opcode: 0xBE,
        addressing_mode: AddressingMode::AbsoluteY,
        cycles: 4,
        length: 3,
        execute: function::ldx,
    },
    Instruction {
        name: "LAX",
        opcode: 0xBF,
        addressing_mode: AddressingMode::AbsoluteY,
        cycles: 4,
        length: 3,
        execute: function::lax,
    },
    Instruction {
        name: "CPY",
        opcode: 0xC0,
        addressing_mode: AddressingMode::Immediate,
        cycles: 2,
        length: 2,
        execute: function::cpy,
    },
    Instruction {
        name: "CMP",
        opcode: 0xC1,
        addressing_mode: AddressingMode::IndirectX,
        cycles: 6,
        length: 2,
        execute: function::cmp,
    },
    Instruction {
        name: "NOP",
        opcode: 0xC2,
        addressing_mode: AddressingMode::Immediate,
        cycles: 2,
        length: 2,
        execute: function::nop,
    },
    Instruction {
        name: "DCP",
        opcode: 0xC3,
        addressing_mode: AddressingMode::IndirectX,
        cycles: 8,
        length: 2,
        execute: function::dcp,
    },
    Instruction {
        name: "CPY",
        opcode: 0xC4,
        addressing_mode: AddressingMode::ZeroPage,
        cycles: 3,
        length: 2,
        execute: function::cpy,
    },
    Instruction {
        name: "CMP",
        opcode: 0xC5,
        addressing_mode: AddressingMode::ZeroPage,
        cycles: 3,
        length: 2,
        execute: function::cmp,
    },
    Instruction {
        name: "DEC",
        opcode: 0xC6,
        addressing_mode: AddressingMode::ZeroPage,
        cycles: 5,
        length: 2,
        execute: function::dec,
    },
    Instruction {
        name: "DCP",
        opcode: 0xC7,
        addressing_mode: AddressingMode::ZeroPage,
        cycles: 5,
        length: 2,
        execute: function::dcp,
    },
    Instruction {
        name: "INY",
        opcode: 0xC8,
        addressing_mode: AddressingMode::Implied,
        cycles: 2,
        length: 1,
        execute: function::iny,
    },
    Instruction {
        name: "CMP",
        opcode: 0xC9,
        addressing_mode: AddressingMode::Immediate,
        cycles: 2,
        length: 2,
        execute: function::cmp,
    },
    Instruction {
        name: "DEX",
        opcode: 0xCA,
        addressing_mode: AddressingMode::Implied,
        cycles: 2,
        length: 1,
        execute: function::dex,
    },
    Instruction {
        name: "AXS",
        opcode: 0xCB,
        addressing_mode: AddressingMode::Immediate,
        cycles: 2,
        length: 2,
        execute: function::axs,
    },
    Instruction {
        name: "CPY",
        opcode: 0xCC,
        addressing_mode: AddressingMode::Absolute,
        cycles: 4,
        length: 3,
        execute: function::cpy,
    },
    Instruction {
        name: "CMP",
        opcode: 0xCD,
        addressing_mode: AddressingMode::Absolute,
        cycles: 4,
        length: 3,
        execute: function::cmp,
    },
    Instruction {
        name: "DEC",
        opcode: 0xCE,
        addressing_mode: AddressingMode::Absolute,
        cycles: 6,
        length: 3,
        execute: function::dec,
    },
    Instruction {
        name: "DCP",
        opcode: 0xCF,
        addressing_mode: AddressingMode::Absolute,
        cycles: 6,
        length: 3,
        execute: function::dcp,
    },
    Instruction {
        name: "BNE",
        opcode: 0xD0,
        addressing_mode: AddressingMode::Relative,
        cycles: 2,
        length: 2,
        execute: function::bne,
    },
    Instruction {
        name: "CMP",
        opcode: 0xD1,
        addressing_mode: AddressingMode::IndirectY,
        cycles: 5,
        length: 2,
        execute: function::cmp,
    },
    Instruction {
        name: "KIL",
        opcode: 0xD2,
        addressing_mode: AddressingMode::Implied,
        cycles: 0,
        length: 1,
        execute: function::kil,
    },
    Instruction {
        name: "DCP",
        opcode: 0xD3,
        addressing_mode: AddressingMode::IndirectY,
        cycles: 8,
        length: 2,
        execute: function::dcp,
    },
    Instruction {
        name: "NOP",
        opcode: 0xD4,
        addressing_mode: AddressingMode::ZeroPageX,
        cycles: 4,
        length: 2,
        execute: function::nop,
    },
    Instruction {
        name: "CMP",
        opcode: 0xD5,
        addressing_mode: AddressingMode::ZeroPageX,
        cycles: 4,
        length: 2,
        execute: function::cmp,
    },
    Instruction {
        name: "DEC",
        opcode: 0xD6,
        addressing_mode: AddressingMode::ZeroPageX,
        cycles: 6,
        length: 2,
        execute: function::dec,
    },
    Instruction {
        name: "DCP",
        opcode: 0xD7,
        addressing_mode: AddressingMode::ZeroPageX,
        cycles: 6,
        length: 2,
        execute: function::dcp,
    },
    Instruction {
        name: "CLD",
        opcode: 0xD8,
        addressing_mode: AddressingMode::Implied,
        cycles: 2,
        length: 1,
        execute: function::cld,
    },
    Instruction {
        name: "CMP",
        opcode: 0xD9,
        addressing_mode: AddressingMode::AbsoluteY,
        cycles: 4,
        length: 3,
        execute: function::cmp,
    },
    Instruction {
        name: "NOP",
        opcode: 0xDA,
        addressing_mode: AddressingMode::Implied,
        cycles: 2,
        length: 1,
        execute: function::nop,
    },
    Instruction {
        name: "DCP",
        opcode: 0xDB,
        addressing_mode: AddressingMode::AbsoluteY,
        cycles: 7,
        length: 3,
        execute: function::dcp,
    },
    Instruction {
        name: "NOP",
        opcode: 0xDC,
        addressing_mode: AddressingMode::AbsoluteX,
        cycles: 4,
        length: 3,
        execute: function::nop,
    },
    Instruction {
        name: "CMP",
        opcode: 0xDD,
        addressing_mode: AddressingMode::AbsoluteX,
        cycles: 4,
        length: 3,
        execute: function::cmp,
    },
    Instruction {
        name: "DEC",
        opcode: 0xDE,
        addressing_mode: AddressingMode::AbsoluteX,
        cycles: 7,
        length: 3,
        execute: function::dec,
    },
    Instruction {
        name: "DCP",
        opcode: 0xDF,
        addressing_mode: AddressingMode::AbsoluteX,
        cycles: 7,
        length: 3,
        execute: function::dcp,
    },
    Instruction {
        name: "CPX",
        opcode: 0xE0,
        addressing_mode: AddressingMode::Immediate,
        cycles: 2,
        length: 2,
        execute: function::cpx,
    },
    Instruction {
        name: "SBC",
        opcode: 0xE1,
        addressing_mode: AddressingMode::IndirectX,
        cycles: 6,
        length: 2,
        execute: function::sbc,
    },
    Instruction {
        name: "KIL",
        opcode: 0xE2,
        addressing_mode: AddressingMode::Implied,
        cycles: 0,
        length: 1,
        execute: function::kil,
    },
    Instruction {
        name: "ISC",
        opcode: 0xE3,
        addressing_mode: AddressingMode::IndirectX,
        cycles: 8,
        length: 2,
        execute: function::isc,
    },
    Instruction {
        name: "NOP",
        opcode: 0xE4,
        addressing_mode: AddressingMode::ZeroPage,
        cycles: 3,
        length: 2,
        execute: function::nop,
    },
    Instruction {
        name: "SBC",
        opcode: 0xE5,
        addressing_mode: AddressingMode::ZeroPage,
        cycles: 3,
        length: 2,
        execute: function::sbc,
    },
    Instruction {
        name: "INC",
        opcode: 0xE6,
        addressing_mode: AddressingMode::ZeroPage,
        cycles: 5,
        length: 2,
        execute: function::inc,
    },
    Instruction {
        name: "ISC",
        opcode: 0xE7,
        addressing_mode: AddressingMode::ZeroPage,
        cycles: 5,
        length: 2,
        execute: function::isc,
    },
    Instruction {
        name: "INX",
        opcode: 0xE8,
        addressing_mode: AddressingMode::Implied,
        cycles: 2,
        length: 1,
        execute: function::inx,
    },
    Instruction {
        name: "SBC",
        opcode: 0xE9,
        addressing_mode: AddressingMode::Immediate,
        cycles: 2,
        length: 2,
        execute: function::sbc,
    },
    Instruction {
        name: "NOP",
        opcode: 0xEA,
        addressing_mode: AddressingMode::Implied,
        cycles: 2,
        length: 1,
        execute: function::nop,
    },
    Instruction {
        name: "SBC",
        opcode: 0xEB,
        addressing_mode: AddressingMode::Immediate,
        cycles: 2,
        length: 2,
        execute: function::sbc,
    },
    Instruction {
        name: "CPX",
        opcode: 0xEC,
        addressing_mode: AddressingMode::Absolute,
        cycles: 4,
        length: 3,
        execute: function::cpx,
    },
    Instruction {
        name: "SBC",
        opcode: 0xED,
        addressing_mode: AddressingMode::Absolute,
        cycles: 4,
        length: 3,
        execute: function::sbc,
    },
    Instruction {
        name: "INC",
        opcode: 0xEE,
        addressing_mode: AddressingMode::Absolute,
        cycles: 6,
        length: 3,
        execute: function::inc,
    },
    Instruction {
        name: "ISC",
        opcode: 0xEF,
        addressing_mode: AddressingMode::Absolute,
        cycles: 6,
        length: 3,
        execute: function::isc,
    },
    Instruction {
        name: "BEQ",
        opcode: 0xF0,
        addressing_mode: AddressingMode::Relative,
        cycles: 2,
        length: 2,
        execute: function::beq,
    },
    Instruction {
        name: "SBC",
        opcode: 0xF1,
        addressing_mode: AddressingMode::IndirectY,
        cycles: 5,
        length: 2,
        execute: function::sbc,
    },
    Instruction {
        name: "KIL",
        opcode: 0xF2,
        addressing_mode: AddressingMode::Implied,
        cycles: 0,
        length: 1,
        execute: function::kil,
    },
    Instruction {
        name: "ISC",
        opcode: 0xF3,
        addressing_mode: AddressingMode::IndirectY,
        cycles: 8,
        length: 2,
        execute: function::isc,
    },
    Instruction {
        name: "NOP",
        opcode: 0xF4,
        addressing_mode: AddressingMode::ZeroPageX,
        cycles: 4,
        length: 2,
        execute: function::nop,
    },
    Instruction {
        name: "SBC",
        opcode: 0xF5,
        addressing_mode: AddressingMode::ZeroPageX,
        cycles: 4,
        length: 2,
        execute: function::sbc,
    },
    Instruction {
        name: "INC",
        opcode: 0xF6,
        addressing_mode: AddressingMode::ZeroPageX,
        cycles: 6,
        length: 2,
        execute: function::inc,
    },
    Instruction {
        name: "ISC",
        opcode: 0xF7,
        addressing_mode: AddressingMode::ZeroPageX,
        cycles: 6,
        length: 2,
        execute: function::isc,
    },
    Instruction {
        name: "SED",
        opcode: 0xF8,
        addressing_mode: AddressingMode::Implied,
        cycles: 2,
        length: 1,
        execute: function::sed,
    },
    Instruction {
        name: "SBC",
        opcode: 0xF9,
        addressing_mode: AddressingMode::AbsoluteY,
        cycles: 4,
        length: 3,
        execute: function::sbc,
    },
    Instruction {
        name: "NOP",
        opcode: 0xFA,
        addressing_mode: AddressingMode::Implied,
        cycles: 2,
        length: 1,
        execute: function::nop,
    },
    Instruction {
        name: "ISC",
        opcode: 0xFB,
        addressing_mode: AddressingMode::AbsoluteY,
        cycles: 7,
        length: 3,
        execute: function::isc,
    },
    Instruction {
        name: "NOP",
        opcode: 0xFC,
        addressing_mode: AddressingMode::AbsoluteX,
        cycles: 4,
        length: 3,
        execute: function::nop,
    },
    Instruction {
        name: "SBC",
        opcode: 0xFD,
        addressing_mode: AddressingMode::AbsoluteX,
        cycles: 4,
        length: 3,
        execute: function::sbc,
    },
    Instruction {
        name: "INC",
        opcode: 0xFE,
        addressing_mode: AddressingMode::AbsoluteX,
        cycles: 7,
        length: 3,
        execute: function::inc,
    },
    Instruction {
        name: "ISC",
        opcode: 0xFF,
        addressing_mode: AddressingMode::AbsoluteX,
        cycles: 7,
        length: 3,
        execute: function::isc,
    },
];